[install]
build = 1

[ui]
is_visible = 1
label = ITSI Design Patterns

[launcher]
author = Splunk, Inc.
description = Tools to help build models, screenshots have some basic docs.
version = 2.1.3

[package]
id = DA-ITSI-CP-CUST-itsi_design_patterns
check_for_updates = false
show_upgrade_notification = false

[triggers]
reload.content_pack_settings = simple

