[idp_base]
action.email.useNSSubject = 1
action.webhook.enable_allowlist = 0
alert.track = 0
description = IDP backend processing search 
disabled = 0
dispatchAs = owner
display.general.timeRangePicker.show = 0
display.general.type = statistics
display.page.search.tab = statistics
request.ui_dispatch_view = search
search = | `idp_get_tiers_and_tech_stack("$lookup$", "$group$", "$lob$", "$system$")`\
`idp_token_substitution`\
`idp_get_service_templates`\
`idp_format_fields`
skip_scheduled_realtime_idxc = 0

[idp_validation]
action.email.useNSSubject = 1
action.webhook.enable_allowlist = 0
alert.track = 0
description = Basic validation of of service lookups for IDP
disabled = 0
dispatchAs = owner
display.general.timeRangePicker.show = 0
display.general.type = statistics
display.page.search.tab = statistics
request.ui_dispatch_view = search
search = | inputlookup $lookup_name$\
| streamstats c as row \
```\
crit:\
 - mandatory fields - group, lob, t1\
 - multiple matches of tech_stack \
warn:\
 - set tech_stack no tech_kind\
 - invalid tech_kind\
 ```\
| lookup idp_tech_stack.csv tech_kind OUTPUT urgency as idpcheck_tech_kind_temp \
| eval tech_stack=if(match(tech_stack,","), split(tech_stack,","), tech_stack)\
| mvexpand tech_stack\
| lookup idp_tech_templates.csv tag as tech_stack OUTPUT template as idpcheck_tech_stack_temp \
| eval check=if((isnotnull(tech_stack) AND match(tech_stack,"\w+")) AND (isnull(tech_kind) OR !match(tech_kind,"\w+")), "tech_stack value is set but no tech_kind value was found. tech will not be included in model", null()),\
       check=if(isnotnull(tech_kind) AND match(tech_kind,"\w+") AND isnull(idpcheck_tech_kind_temp), mvappend(check,"Invalid value of tech_kind found, tech will not be included in model. Check idp_tech_kind.csv"), check),\
       severity="3",\
       warncount=coalesce(mvcount(check),0),\
       check=if(mvcount(idpcheck_tech_stack_temp)>1, mvappend(check,"Multiple matches found for tech_stack value. Check idp_tech_templates.csv"), check)\
| foreach group lob t1 \
    [ eval temp_check=case(isnull(<<FIELD>>), if(isnull(temp_check), "<<FIELD>>", printf("%s,%s",temp_check,<<FIELD>>))) ]\
| eval check=if(isnotnull(temp_check), mvappend(check, printf("Mandatory field(s) missing: %s", temp_check)), check), \
       severity=if(warncount!=mvcount(check), 1, severity)    \
\
| fields check, row, severity \
| eventstats max(eval(len(row))) as maxlen \
| eval row=if(isnotnull(row),printf("%s%s",substr("000000", 1, maxlen-len(row)),row), null()) \
\
| stats values(row) as row max(severity) as severity by check \
| eval row=mvjoin(row,",") \
| sort severity \
| fillnull value="all" row \
| eval result=case(severity==1, "Failed", severity==3, "Pass", true(), null()),\
       severity=case(severity==1, "critical", severity==3, "warning")\
| fields result, row, check, severity
